services:
  damoclesgil:
    image: node:22
    ports:
      - 4321:4321
    working_dir: /app
    command: sh -c "npm install -g npm@11.2.0 && npm install && npm run dev:host"
    volumes:
      - ./:/app
      - /app/node_modules

      # Para rodar isso no windows é necessário desabilitar o firewall do windows